# Generated by Django 3.1.5 on 2024-10-01 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='分类名称')),
                ('logo', models.ImageField(default='', upload_to='uploads/goods_img/', verbose_name='分类logo图片')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否显示在导航栏')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_cat', to='app8.goodscategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': '商品分类',
                'db_table': 'd_goods_category8',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='市场价格')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='实际价格')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='计量单位')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('amount', models.IntegerField(default=0, verbose_name='销售量')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '下架')], default=0)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品主图')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('createDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app8.goodscategory', verbose_name='商品分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品表',
                'db_table': 'd_goods8',
            },
        ),
    ]
