# Generated by Django 3.1.5 on 2024-10-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (['check_myuser', '审核用户信息'],), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
