# Generated by Django 3.1.5 on 2024-10-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('cardno', models.CharField(max_length=30, verbose_name='卡号')),
                ('bank', models.CharField(max_length=30, verbose_name='所属银行')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercard', to='app4.userbaseinfo')),
            ],
            options={
                'verbose_name': '用户卡信息',
                'db_table': 'CardInfo',
                'managed': True,
            },
        ),
    ]
