# Generated by Django 3.1.5 on 2024-10-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_cardinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.userbaseinfo'),
        ),
    ]
