# Generated by Django 3.1.5 on 2024-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名称')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('status', models.CharField(max_length=1, verbose_name='状态')),
                ('createdate', models.DateTimeField(auto_now=True, db_column='createDate', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '人员基本信息',
                'db_table': 'UserBaseInfo5',
                'managed': True,
            },
        ),
    ]
