# Generated by Django 4.2.16 on 2024-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic", "0002_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
