# Generated by Django 3.1.5 on 2024-09-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20240930_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaseinfo',
            name='createdate',
            field=models.DateTimeField(db_column='createDate', verbose_name='创建日期'),
        ),
    ]
