# Generated by Django 3.1.5 on 2024-09-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20240930_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbaseinfo',
            name='createdate',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
    ]
