# Generated by Django 3.1.5 on 2024-10-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='分类名称')),
                ('sort', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品分类',
                'db_table': 'd_goods_category9',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市场价格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='实际价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app9.goodscategory', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品表',
                'db_table': 'd_goods9',
            },
        ),
    ]
